version: '3.8'
services:
  valorant-bot:
    image: ghcr.io/notbjoggisatall/valorant-bot:1.0
    restart: always
    container_name: valorant-bot
    environment:
      - SPRING_PROFILES_ACTIVE=docker,prod
    volumes:
      - 'utils:/utils'
    networks:
      - 'internal'
networks:
  internal:
    external: true
volumes:
  utils:
    external: true
